ARG BASE_IMAGE=ghcr.io/akulatraxas/akutest/pretalx-worker:latest
ARG VERSION=latest
FROM ${BASE_IMAGE}

USER pretalxuser
VOLUME ["/etc/pretalx", "/data", "/public"]
ENTRYPOINT ["pretalx"]
CMD ["taskworker"]
