FROM ghcr.io/akulatraxas/pretalx-base:latest

RUN \
        apt-get install -y  nodejs \
        apt-get clean && \
        dpkg-reconfigure locales && \
        locale-gen C.UTF-8 && \
        /usr/sbin/update-locale LANG=C.UTF-8

WORKDIR /var/pretalx
VOLUME ["/etc/pretalx", "/data", "/public"]
EXPOSE 80
ENTRYPOINT [ "entrypoint.sh" ]
CMD [ "run" ]
